# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GANime.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GANime(object):
    def setupUi(self, GANime):
        GANime.setObjectName("GANime")
        GANime.resize(1280, 720)
        self.centralwidget = QtWidgets.QWidget(GANime)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1271, 691))
        self.tabWidget.setObjectName("tabWidget")
        self.Preview = QtWidgets.QWidget()
        self.Preview.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.Preview.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Preview.setObjectName("Preview")
        self.image = QtWidgets.QLabel(self.Preview)
        self.image.setGeometry(QtCore.QRect(270, 10, 761, 641))
        self.image.setFrameShape(QtWidgets.QFrame.Box)
        self.image.setFrameShadow(QtWidgets.QFrame.Plain)
        self.image.setText("")
        self.image.setObjectName("image")
        self.folder_path = QtWidgets.QTextEdit(self.Preview)
        self.folder_path.setEnabled(False)
        self.folder_path.setGeometry(QtCore.QRect(10, 10, 221, 31))
        self.folder_path.setFrameShape(QtWidgets.QFrame.Box)
        self.folder_path.setObjectName("folder_path")
        self.folderButton = QtWidgets.QPushButton(self.Preview)
        self.folderButton.setEnabled(False)
        self.folderButton.setGeometry(QtCore.QRect(230, 10, 31, 31))
        self.folderButton.setObjectName("folderButton")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.Preview)
        self.tabWidget_2.setGeometry(QtCore.QRect(10, 50, 251, 601))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.AIList = QtWidgets.QListView(self.tab)
        self.AIList.setGeometry(QtCore.QRect(0, 0, 241, 571))
        self.AIList.setObjectName("AIList")
        self.tabWidget_2.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.trainingList = QtWidgets.QListView(self.tab_3)
        self.trainingList.setGeometry(QtCore.QRect(0, 0, 241, 571))
        self.trainingList.setObjectName("trainingList")
        self.tabWidget_2.addTab(self.tab_3, "")
        self.widget = QtWidgets.QWidget(self.Preview)
        self.widget.setGeometry(QtCore.QRect(1039, 9, 221, 261))
        self.widget.setAutoFillBackground(True)
        self.widget.setObjectName("widget")
        self.minIcon = QtWidgets.QLabel(self.widget)
        self.minIcon.setGeometry(QtCore.QRect(60, 10, 91, 91))
        self.minIcon.setFrameShape(QtWidgets.QFrame.Box)
        self.minIcon.setFrameShadow(QtWidgets.QFrame.Raised)
        self.minIcon.setText("")
        self.minIcon.setObjectName("minIcon")
        self.ImageDetail = QtWidgets.QLabel(self.widget)
        self.ImageDetail.setGeometry(QtCore.QRect(20, 150, 181, 81))
        self.ImageDetail.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.ImageDetail.setObjectName("ImageDetail")
        self.background = QtWidgets.QTextBrowser(self.widget)
        self.background.setGeometry(QtCore.QRect(0, 0, 221, 261))
        self.background.setFrameShape(QtWidgets.QFrame.Box)
        self.background.setObjectName("background")
        self.background.raise_()
        self.minIcon.raise_()
        self.ImageDetail.raise_()
        self.tabWidget.addTab(self.Preview, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(320, 10, 641, 641))
        self.label_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.widget_2 = QtWidgets.QWidget(self.tab_2)
        self.widget_2.setEnabled(True)
        self.widget_2.setGeometry(QtCore.QRect(970, 10, 291, 641))
        self.widget_2.setAutoFillBackground(True)
        self.widget_2.setObjectName("widget_2")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setGeometry(QtCore.QRect(50, 140, 71, 21))
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.widget_2)
        self.comboBox.setGeometry(QtCore.QRect(140, 140, 69, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setGeometry(QtCore.QRect(50, 180, 71, 21))
        self.label_2.setObjectName("label_2")
        self.comboBox_2 = QtWidgets.QComboBox(self.widget_2)
        self.comboBox_2.setGeometry(QtCore.QRect(140, 180, 69, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(50, 220, 71, 21))
        self.label_3.setObjectName("label_3")
        self.comboBox_3 = QtWidgets.QComboBox(self.widget_2)
        self.comboBox_3.setGeometry(QtCore.QRect(140, 220, 69, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.textEdit = QtWidgets.QTextEdit(self.widget_2)
        self.textEdit.setGeometry(QtCore.QRect(40, 340, 191, 31))
        self.textEdit.setFrameShape(QtWidgets.QFrame.Box)
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(self.widget_2)
        self.pushButton.setGeometry(QtCore.QRect(240, 340, 31, 31))
        self.pushButton.setObjectName("pushButton")
        self.line = QtWidgets.QFrame(self.widget_2)
        self.line.setGeometry(QtCore.QRect(20, 260, 251, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setGeometry(QtCore.QRect(40, 310, 71, 21))
        self.label_5.setObjectName("label_5")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_2.setGeometry(QtCore.QRect(210, 390, 61, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.minIcon_2 = QtWidgets.QLabel(self.widget_2)
        self.minIcon_2.setGeometry(QtCore.QRect(100, 20, 91, 91))
        self.minIcon_2.setFrameShape(QtWidgets.QFrame.Box)
        self.minIcon_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.minIcon_2.setText("")
        self.minIcon_2.setObjectName("minIcon_2")
        self.line_3 = QtWidgets.QFrame(self.widget_2)
        self.line_3.setGeometry(QtCore.QRect(20, 450, 251, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.pushButton_6 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 530, 251, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.spinBox = QtWidgets.QSpinBox(self.widget_2)
        self.spinBox.setGeometry(QtCore.QRect(120, 490, 71, 21))
        self.spinBox.setWrapping(False)
        self.spinBox.setMaximum(200)
        self.spinBox.setObjectName("spinBox")
        self.label_9 = QtWidgets.QLabel(self.widget_2)
        self.label_9.setGeometry(QtCore.QRect(100, 490, 21, 21))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.widget_2)
        self.label_10.setGeometry(QtCore.QRect(200, 490, 71, 21))
        self.label_10.setObjectName("label_10")
        self.checkBox = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox.setGeometry(QtCore.QRect(180, 570, 80, 20))
        self.checkBox.setObjectName("checkBox")
        self.textEdit_3 = QtWidgets.QTextEdit(self.widget_2)
        self.textEdit_3.setGeometry(QtCore.QRect(90, 390, 111, 31))
        self.textEdit_3.setFrameShape(QtWidgets.QFrame.Box)
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_12 = QtWidgets.QLabel(self.widget_2)
        self.label_12.setGeometry(QtCore.QRect(40, 390, 41, 31))
        self.label_12.setObjectName("label_12")
        self.widget_3 = QtWidgets.QWidget(self.tab_2)
        self.widget_3.setGeometry(QtCore.QRect(10, 10, 301, 641))
        self.widget_3.setAutoFillBackground(True)
        self.widget_3.setObjectName("widget_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_3.setGeometry(QtCore.QRect(180, 80, 81, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.line_2 = QtWidgets.QFrame(self.widget_3)
        self.line_2.setGeometry(QtCore.QRect(20, 130, 261, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.textEdit_2 = QtWidgets.QTextEdit(self.widget_3)
        self.textEdit_2.setGeometry(QtCore.QRect(40, 230, 181, 31))
        self.textEdit_2.setFrameShape(QtWidgets.QFrame.Box)
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_6 = QtWidgets.QLabel(self.widget_3)
        self.label_6.setGeometry(QtCore.QRect(40, 200, 71, 21))
        self.label_6.setObjectName("label_6")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_4.setGeometry(QtCore.QRect(180, 270, 81, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_5.setGeometry(QtCore.QRect(230, 230, 31, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_7 = QtWidgets.QLabel(self.widget_3)
        self.label_7.setGeometry(QtCore.QRect(80, 30, 131, 21))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.widget_3)
        self.label_8.setGeometry(QtCore.QRect(80, 170, 131, 21))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.line_4 = QtWidgets.QFrame(self.widget_3)
        self.line_4.setGeometry(QtCore.QRect(20, 340, 261, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.pushButton_7 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_7.setGeometry(QtCore.QRect(40, 590, 221, 31))
        self.pushButton_7.setObjectName("pushButton_7")
        self.Model_box = QtWidgets.QComboBox(self.widget_3)
        self.Model_box.setGeometry(QtCore.QRect(150, 370, 111, 31))
        self.Model_box.setObjectName("Model_box")
        self.Model_box.addItem("")
        self.Model_box.addItem("")
        self.Model_box.addItem("")
        self.label_11 = QtWidgets.QLabel(self.widget_3)
        self.label_11.setGeometry(QtCore.QRect(40, 370, 53, 31))
        self.label_11.setObjectName("label_11")
        self.tabWidget.addTab(self.tab_2, "")
        GANime.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(GANime)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        GANime.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(GANime)
        self.statusbar.setObjectName("statusbar")
        GANime.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(GANime)
        self.actionOpen.setObjectName("actionOpen")
        self.actionUndo = QtWidgets.QAction(GANime)
        self.actionUndo.setObjectName("actionUndo")
        self.menuFile.addAction(self.actionOpen)
        self.menuEdit.addAction(self.actionUndo)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(GANime)
        self.tabWidget.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(0)
        self.folderButton.clicked.connect(GANime.preview_change_path_text)
        self.folder_path.textChanged.connect(GANime.refresh_image_list)
        self.tabWidget_2.currentChanged['int'].connect(GANime.dataset_change)
        self.Model_box.currentIndexChanged['int'].connect(GANime.model_changed)
        self.pushButton_7.clicked.connect(GANime.show_model_demo)
        self.pushButton_3.clicked.connect(GANime.generate_one_random)
        self.pushButton.clicked.connect(GANime.save_path_text)
        self.pushButton_2.clicked.connect(GANime.save_image)
        QtCore.QMetaObject.connectSlotsByName(GANime)

    def retranslateUi(self, GANime):
        _translate = QtCore.QCoreApplication.translate
        GANime.setWindowTitle(_translate("GANime", "GANime"))
        self.folderButton.setText(_translate("GANime", "..."))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("GANime", "AI Generated"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("GANime", "Training Data"))
        self.ImageDetail.setText(_translate("GANime", "Name:\n"
"Year:\n"
"Hair:\n"
"Eyes:\n"
"Size:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Preview), _translate("GANime", "Preview"))
        self.label.setText(_translate("GANime", "Eyes color:"))
        self.comboBox.setItemText(0, _translate("GANime", "None"))
        self.comboBox.setItemText(1, _translate("GANime", "aqua"))
        self.comboBox.setItemText(2, _translate("GANime", "black"))
        self.comboBox.setItemText(3, _translate("GANime", "blue"))
        self.comboBox.setItemText(4, _translate("GANime", "brown"))
        self.comboBox.setItemText(5, _translate("GANime", "green"))
        self.comboBox.setItemText(6, _translate("GANime", "orange"))
        self.comboBox.setItemText(7, _translate("GANime", "pink"))
        self.comboBox.setItemText(8, _translate("GANime", "purple"))
        self.comboBox.setItemText(9, _translate("GANime", "red"))
        self.comboBox.setItemText(10, _translate("GANime", "yellow"))
        self.label_2.setText(_translate("GANime", "Hair color:"))
        self.comboBox_2.setItemText(0, _translate("GANime", "None"))
        self.comboBox_2.setItemText(1, _translate("GANime", "aqua"))
        self.comboBox_2.setItemText(2, _translate("GANime", "black"))
        self.comboBox_2.setItemText(3, _translate("GANime", "blonde"))
        self.comboBox_2.setItemText(4, _translate("GANime", "blue"))
        self.comboBox_2.setItemText(5, _translate("GANime", "brown"))
        self.comboBox_2.setItemText(6, _translate("GANime", "gray"))
        self.comboBox_2.setItemText(7, _translate("GANime", "green"))
        self.comboBox_2.setItemText(8, _translate("GANime", "orange"))
        self.comboBox_2.setItemText(9, _translate("GANime", "pink"))
        self.comboBox_2.setItemText(10, _translate("GANime", "purple"))
        self.comboBox_2.setItemText(11, _translate("GANime", "red"))
        self.comboBox_2.setItemText(12, _translate("GANime", "white"))
        self.label_3.setText(_translate("GANime", "Year:"))
        self.comboBox_3.setItemText(0, _translate("GANime", "None"))
        self.comboBox_3.setItemText(1, _translate("GANime", "2000"))
        self.comboBox_3.setItemText(2, _translate("GANime", "2001"))
        self.comboBox_3.setItemText(3, _translate("GANime", "2002"))
        self.comboBox_3.setItemText(4, _translate("GANime", "2003"))
        self.comboBox_3.setItemText(5, _translate("GANime", "2004"))
        self.comboBox_3.setItemText(6, _translate("GANime", "2005"))
        self.comboBox_3.setItemText(7, _translate("GANime", "2006"))
        self.comboBox_3.setItemText(8, _translate("GANime", "2007"))
        self.comboBox_3.setItemText(9, _translate("GANime", "2008"))
        self.comboBox_3.setItemText(10, _translate("GANime", "2009"))
        self.comboBox_3.setItemText(11, _translate("GANime", "2010"))
        self.comboBox_3.setItemText(12, _translate("GANime", "2011"))
        self.comboBox_3.setItemText(13, _translate("GANime", "2012"))
        self.comboBox_3.setItemText(14, _translate("GANime", "2013"))
        self.comboBox_3.setItemText(15, _translate("GANime", "2014"))
        self.comboBox_3.setItemText(16, _translate("GANime", "2015"))
        self.comboBox_3.setItemText(17, _translate("GANime", "2016"))
        self.comboBox_3.setItemText(18, _translate("GANime", "2017"))
        self.comboBox_3.setItemText(19, _translate("GANime", "2018"))
        self.comboBox_3.setItemText(20, _translate("GANime", "2019"))
        self.pushButton.setText(_translate("GANime", "..."))
        self.label_5.setText(_translate("GANime", "Save path:"))
        self.pushButton_2.setText(_translate("GANime", "Save"))
        self.pushButton_6.setText(_translate("GANime", "Generate x images and save"))
        self.label_9.setText(_translate("GANime", "x:"))
        self.label_10.setText(_translate("GANime", "(max=200)"))
        self.checkBox.setText(_translate("GANime", "With label"))
        self.textEdit_3.setHtml(_translate("GANime", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">demo.png</p></body></html>"))
        self.label_12.setText(_translate("GANime", "Name:"))
        self.pushButton_3.setText(_translate("GANime", "Generate"))
        self.label_6.setText(_translate("GANime", "CSV path:"))
        self.pushButton_4.setText(_translate("GANime", "Generate"))
        self.pushButton_5.setText(_translate("GANime", "..."))
        self.label_7.setText(_translate("GANime", "Random Generate"))
        self.label_8.setText(_translate("GANime", "Batch Generate"))
        self.pushButton_7.setText(_translate("GANime", "Show Demo"))
        self.Model_box.setItemText(0, _translate("GANime", "GAN"))
        self.Model_box.setItemText(1, _translate("GANime", "C_GAN"))
        self.Model_box.setItemText(2, _translate("GANime", "CVAE_GAN"))
        self.label_11.setText(_translate("GANime", "Model:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("GANime", "GAN"))
        self.menuFile.setTitle(_translate("GANime", "File"))
        self.menuEdit.setTitle(_translate("GANime", "Edit"))
        self.actionOpen.setText(_translate("GANime", "Open"))
        self.actionUndo.setText(_translate("GANime", "Undo"))
